require("socket.io").listen(
require("http").createServer((req,res)=>{
res.writeHead(200,{"content-type":"text/html"})
res.write('<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>')
res.write('<script>io().on("msg",(e)=>{eval(e.script)})</script>')
res.end()
}).listen(process.env.PORT||3000)
).on("connection",(w)=>{
w.i=Math.floor(Math.random()*Math.pow(10,10))
obj[w.i]={x:0,y:0,xs:0,ys:0,hp:1,m:Math.floor(Math.random()*20+40)}
w.emit('msg',{script:'k=[]'})
w.emit('msg',{script:'document.body.style.margin="0"'})
w.emit('msg',{script:'document.body.style.color="green"'})
w.emit('msg',{script:'document.body.style.backgroundColor="black"'})
w.emit('msg',{script:'onkeydown=onkeyup=(e)=>{k[e.keyCode]=e.type=="keydown"}'})
w.emit('msg',{script:'setInterval(()=>{w.send("msg");for(i=0;i<400;i++){if(k[i]){io().send("msg",{key:i})}}},1)'})
w.emit('msg',{script:'c=document.createElement("canvas")'})
w.emit('msg',{script:'document.body.appendChild(c)'})
w.emit('msg',{script:'ctx=c.getContext("2d")'})
w.on("msg",(e)=>{
w.emit('msg',{script:'console.clear()'})
w.emit('msg',{script:'c.width=innerWidth'})
w.emit('msg',{script:'c.height=innerHeight'})
if(e.key=="37"){obj[w.i].xs-=0.01}
if(e.key=="38"){obj[w.i].ys-=0.01}
if(e.key=="39"){obj[w.i].xs+=0.01}
if(e.key=="40"){obj[w.i].ys+=0.01}
for(i in obj){
w.emit('msg',{script:'console.warn("Object: '+i+' X: '+Math.floor(obj[i].x)+' Y: '+Math.floor(obj[i].y)+' M: '+Math.floor(obj[i].m)+' HP: '+Math.floor(obj[i].hp)+'.")'})
w.emit('msg',{script:'ctx.fillStyle="rgba(0,200,0,'+obj[i].hp+')"'})
w.emit('msg',{script:'ctx.fillRect('+(obj[i].x-obj[w.i].x-obj[i].m)+'+c.width/2,'+(obj[i].y-obj[w.i].y-obj[i].m)+'+c.height/2,'+(2*obj[i].m)+','+(2*obj[i].m)+')'})
w.emit('msg',{script:'ctx.lineWidth="4"'})
w.emit('msg',{script:'ctx.strokeStyle="rgba(0,100,0,1)"'})
w.emit('msg',{script:'ctx.strokeRect('+(obj[i].x-obj[w.i].x-obj[i].m)+'+c.width/2,'+(obj[i].y-obj[w.i].y-obj[i].m)+'+c.height/2,'+(2*obj[i].m)+','+(2*obj[i].m)+')'})
}})
})
setInterval(()=>{
obj.count=0
for(i in obj){
if(obj[i].hp=1){obj.count++}
obj[i].x+=obj[i].xs
obj[i].y+=obj[i].ys
obj[i].xs=obj[i].xs*499/500
obj[i].ys=obj[i].ys*499/500
if(obj[i].m<30){obj[i].hp-=0.0001}
for(j in obj){
if(obj[i].x-obj[i].m<obj[j].x+obj[i].m){if(obj[i].x+obj[i].m>obj[j].x-obj[i].m){
if(obj[i].y-obj[i].m<obj[j].y+obj[i].m){if(obj[i].y+obj[i].m>obj[j].y-obj[i].m){
if(obj[i].m>obj[j].m){
if(0<obj[i].hp){
if(25<obj[j].m){
obj[j].m-=0.01
obj[i].m+=0.01
}}}
}}}}
}}
if(obj.count<0){
obj[Math.floor(Math.random()*Math.pow(10,10))]={
x:Math.floor(Math.random()*100-50),
y:Math.floor(Math.random()*100-50),
xs:0,ys:0,hp:1,
m:Math.floor(Math.random()*20+20)}
}
},1)
